### PR TITLE
Rename sv.ftl to cosmic_files.ftl

### PR DESCRIPTION
**Pull request by bittin**
Rename the file so the Swedish translation works
as talked with about f0x on the Mattermost 

sorry i screwed up :(

### CODE REVIEW

**Comment by bittin** [comment]
and maybe the folder should be named sv instead of sv-SE to be picked up, sorry for the hassle

**Review by jackpot51 — APPROVED** [review]

**Comment by bittin** [comment]
@jackpot51 not sure if you have to rename the name of the folder from sv_SE to sv too 

maybe it would be good to rename it to sv and keep that as a standard for the Swedish translations
sorry for using the wrong folder name if that is a problem?

**Comment by bittin** [comment]
@jackpot51 more Swedish then no Swedish now atleast but still 9-11 strings that are missing so guess i have to fix that after eating lunch 😛

**Comment by bittin** [comment]
@jackpot51 see PR: #434

**Pull request merged**
