### PR TITLE
Filtering of files in search

### PR DESCRIPTION
**Pull request by leb-kuchen**
This kinda works like in nautilis, so only path forward.

### CODE REVIEW

**Comment by jackpot51** [comment]
Are there missing changes that go with this?

**Comment by leb-kuchen** [comment]
You can only filter the items in the list, else you would have to update it each time the search changes.

**Comment by jackpot51** [comment]
There are some issues with this. When it filters it shows the empty folder icon and text and doesn't indicate that search is hiding items. That location editing is not meant to be used for search, it should offer to autocomplete the path instead.

**Comment by leb-kuchen** [comment]
1 Search and 1 Autocomplete?

**Pull request closed without merging**
