### PR TITLE
Recents section

### LINKED ISSUE #165: Feature Request: "Recents" section
I use the "Recent" section in Gnome files all the time. When I run macOS and Windows, I use it all the time too. It's especially helpful after downloading a file from the internet.

### PR DESCRIPTION
**Pull request by francesco-gaglione**
Close #165

### CODE REVIEW

**Comment by francesco-gaglione** [comment]
The icon in the navbar is not correct, I will fix it asap

**Comment by francesco-gaglione** [comment]
Icons fixed, ready to review and merge

**Comment by jackpot51** [comment]
The recents should also be appended to when cosmic-files is used in dialog mode to open files. Otherwise, this will only show files opened using the GTK file dialog.

**Comment by francesco-gaglione** [comment]
@jackpot51 sorry for the question i am still unfamiliar with the whole repository. So you mean to add the recent section to the navbar? So in the `init` function of the `dialog.rs` file? I've tried doing that but it still doesn't show, could it depend on how the dialog is opened on my OS or is that not the correct place to handle the case?

**Comment by jackpot51** [comment]
You don't have to add anything to Cargo.toml, just use `cargo run --release --example dialog`. Opening a file in the dialog should add it to the recents.

**Comment by francesco-gaglione** [comment]
waiting for https://github.com/pop-os/recently-used-xbel/pull/1 to complete this pr

**Comment by francesco-gaglione** [comment]
@jackpot51 Now both in dialog mode and not when opening a file, it is updated (or added) to recent files

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
